### ISSUE TITLE
大佬求推荐 支持的面板 

### ISSUE THREAD

**Issue by Phil2048** [zhanggaolei001/JdLoginTool#1]
推荐下面板 支持 远程推ck

**Comment by zhanggaolei001** [comment]
https://github.com/lan-tianxiang/JS_TOOL/blob/A1/panel/server.js
这个面板里面添加我README中的代码就可以了,我已经提了PR给大佬作者了

**Comment by zhanggaolei001** [comment]
https://github.com/zhanggaolei001/raypanel
这个我拿以前的面板改的
