### ISSUE TITLE
blocked

### ISSUE THREAD

**Issue by xiaoqi2020** [zhanggaolei001/JdLoginTool#5]
此版主是个超级傻逼，智障

**Comment by xiaoqi2020** [comment]
忘记附带组件了

**Comment by xiaoqi2020** [comment]
分享链接：http://www.scssxhg.com:8888/#s/7lxnKFLQ
访问密码：s3w8I

**Comment by zhanggaolei001** [comment]
源码呢?

**Comment by zhanggaolei001** [comment]
> 软件为本人采用易语言编写，可能会报毒，但是保证100%无毒，不需要任何依赖文件 分享链接：http://www.scssxhg.com:8888/#s/7lwSnbJQ 访问密码：sj0zY

没有源码,我怀疑你想偷ck,没毛病吧?

**Comment by xiaoqi2020** [comment]
你没问题吧？我凭什么要给你源码？你咋不去问腾讯，问阿里要源码呢？你也没有他们的源码，不怀疑他们偷你钱？


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月29日 08:39:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhanggaolei001/JdLoginTool] 送上另一个版本的ck获取工具 (Issue #5)




  
软件为本人采用易语言编写，可能会报毒，但是保证100%无毒，不需要任何依赖文件 分享链接：http://www.scssxhg.com:8888/#s/7lwSnbJQ 访问密码：sj0zY
  
没有源码,我怀疑你想偷ck,没毛病吧?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhanggaolei001** [comment]
1.如果你真没有偷ck,我跟你道歉.
2.问腾讯阿里要源码这种话能说出口,你说话请经过一下脑子.
3.最后,我是说我怀疑,并没有说一定,如果你没有,你可以选择正确方式证明你自己,你在我的repo中发无源码程序,我有必要提醒大家,请你理解,不理解就去好好学习.

**Comment by xiaoqi2020** [comment]
> 1.如果你真没有偷ck,我跟你道歉. 2.问腾讯阿里要源码这种话能说出口,你说话请经过一下脑子. 3.最后,我是说我怀疑,并没有说一定,如果你没有,你可以选择正确方式证明你自己,你在我的repo中发无源码程序,我有必要提醒大家,请你理解,不理解就去好好学习.

麻烦你说话也经过一下脑子，你好好问一下我还可以发出来，一来就这样那样的，你以为你谁啊？

**Comment by xiaoqi2020** [comment]
本来就几句代码，发出来没有任何问题，可是你这样质问我就无法满足你！

**Comment by zhanggaolei001** [comment]
谁稀罕你代码?太把自己当回事儿了吧?

**Comment by xiaoqi2020** [comment]
你是不是太把自己当回事了？

**Comment by xiaoqi2020** [comment]
> 你是不是太把自己当回事了？

另外老子告诉你，老子也没有用你这套抄袭的代码，你也是拿着别人的作品，硬说是自己的创意！智障

**Comment by zhanggaolei001** [comment]
我说你抄我代码了???脑子有病早治疗!

**Comment by xiaoqi2020** [comment]
说你是智障还不承认，连字都不认识！






蓝银派单管家
蓝银物业


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhanggaolei001/JdLoginTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 上午10:07
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [zhanggaolei001/JdLoginTool] 禁止下载(注意:版主是S比) (Issue #5)





 
我说你抄我代码了???脑子有病早治疗!
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhanggaolei001** [comment]
滚?

**Comment by xiaoqi2020** [comment]
> 滚?

你滚给老子 看看，草拟吗的sb

**Comment by xiaoqi2020** [comment]
> 滚?

你特码就是个智障

**Comment by xiaoqi2020** [comment]
老子就没见过你这种智障

**Comment by xiaoqi2020** [comment]
尼玛是怎么生出来你这种智障的？

**Comment by zhanggaolei001** [comment]
老子地盘不欢迎你,滚,别不要脸的刷存在感了



***@***.***
 
发件人： xiaoqi2020
发送时间： 2021-12-01 18:48
收件人： zhanggaolei001/JdLoginTool
抄送： zhanggaolei001; Comment
主题： Re: [zhanggaolei001/JdLoginTool] 禁止下载(注意:版主是S比) (Issue #5)
尼玛是怎么生出来你这种智障的？
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
